logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: always
spring:
  session:
    store-type: redis
  datasource:
      url: jdbc:mysql://localhost:3306/springtutorial
      username: root
      password: ""
  jpa:
    hibernate:
      ddl-auto: create
zuul:
  routes:
    ui:
      url: http://localhost:8081
      sensitive-headers:
    admin:
      url: http://localhost:8082
      sensitive-headers:
    resource:
      url: http://localhost:9000
      sensitive-headers:
